/**
 * An install must leave ClauKit's docs byte-identical to what the package ships.
 *
 * Every retirement and refresh decision in `retired-files.js` is a digest match
 * against blobs from git history. `ck init` used to rewrite every shipped doc in
 * place right after copying it — `relocateDocRefs` turned each bare `scripts/ck/`
 * into `.claude/scripts/ck/`, `migrateDocRefs` each shipped `.js` helper path into
 * `.cjs` — including the copy it had just written from the current package. A
 * doc that so much as *mentioned* the legacy root path ("not root `scripts/ck/`")
 * came out of a fresh install with a digest no release ever shipped, so no later
 * upgrade could prove it was ClauKit's: STALE never refreshed it, RETIRED never
 * removed it. And the rewrite turned the sentence into nonsense.
 *
 * Two halves, tested separately: a fresh install mutates nothing it just copied,
 * and a doc an older `ck init` already mutated is still recognised as shipped.
 */

const { test, before, after } = require('node:test');
const assert = require('node:assert');
const { spawnSync } = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { STALE } = require('../bin/lib/retired-files');
const { matchesShipped } = require('../bin/lib/install-rewrites');
const { REF_PATTERN: RELOCATE_PATTERN, NEW_ROOT } = require('../bin/lib/relocate-scripts');
const { digestOfBuffer } = require('../bin/lib/blob-digest');
const { resolveSourcePath } = require('../bin/lib/kit-resolver');

const REPO = path.join(__dirname, '..');
const CK = path.join(REPO, 'bin', 'ck.js');
const DOC_EXT = new Set(['.md', '.sh', '.ps1', '.yml', '.yaml', '.template']);

let work;
before(() => { work = fs.mkdtempSync(path.join(os.tmpdir(), 'ck-fidelity-')); });
after(() => fs.rmSync(work, { recursive: true, force: true }));

const blob = (sha) => spawnSync('git', ['cat-file', 'blob', sha], { cwd: REPO, maxBuffer: 1 << 24 }).stdout;
const init = (d, kit = 'engineer') => spawnSync('node', [CK, 'init', '--kit', kit], { cwd: d, encoding: 'utf-8' });

function project() {
  const d = fs.mkdtempSync(path.join(work, 'p-'));
  spawnSync('git', ['init', '-q', '.'], { cwd: d });
  fs.writeFileSync(path.join(d, 'package.json'), JSON.stringify({ name: 'host', version: '1.0.0' }, null, 2));
  return d;
}

function docsUnder(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { if (e.name !== 'node_modules') docsUnder(p, out); }
    else if (DOC_EXT.has(path.extname(e.name))) out.push(p);
  }
  return out;
}

/** A bare `scripts/ck/` — non-global, so `.test` carries no `lastIndex` between calls. */
const LEGACY_ROOT = new RegExp(RELOCATE_PATTERN.source);

/** What an older `ck init` did to a doc it had just copied. */
const oldInstallerRewrite = (text) => text.replace(RELOCATE_PATTERN, `${NEW_ROOT}/`);

test('a fresh install leaves every shipped doc byte-identical to its source', () => {
  const p = project();
  const res = init(p, 'both');
  assert.strictEqual(res.status, 0, res.stderr);

  const drifted = [];
  for (const abs of docsUnder(path.join(p, '.claude'))) {
    const rel = path.relative(p, abs).split(path.sep).join('/');
    const src = resolveSourcePath(rel);
    if (!fs.existsSync(src)) continue; // generated by the installer, not copied
    if (!fs.readFileSync(abs).equals(fs.readFileSync(src))) drifted.push(rel);
  }
  assert.deepStrictEqual(drifted, [],
    'the installer rewrote docs it had just copied — their digests now match no shipped blob');
});

test('a doc an older installer rewrote is still proven shipped', () => {
  const entry = STALE.find((e) => e.path === '.claude/workflows/development-rules.md');
  assert.ok(entry, 'fixture: development-rules.md must be a STALE entry');
  const sha = entry.sha.find((s) => LEGACY_ROOT.test(blob(s).toString('utf-8')));
  assert.ok(sha, 'fixture: some shipped version must mention the legacy root path');

  const installed = Buffer.from(oldInstallerRewrite(blob(sha).toString('utf-8')), 'utf-8');
  assert.notStrictEqual(digestOfBuffer(installed), sha, 'fixture: the rewrite must change the digest');
  assert.ok(matchesShipped(installed, entry.sha), 'the rewritten copy is ClauKit\'s and must be recognised');
  assert.ok(!matchesShipped(Buffer.concat([installed, Buffer.from('\nmy edit\n')]), entry.sha),
    'a copy the user edited must not be');
});

test('upgrade: a doc an older installer rewrote is refreshed, not stranded', () => {
  const entry = STALE.find((e) => e.path === '.claude/workflows/development-rules.md');
  const sha = entry.sha.find((s) => LEGACY_ROOT.test(blob(s).toString('utf-8')));
  const p = project();
  assert.strictEqual(init(p).status, 0);

  const abs = path.join(p, entry.path);
  fs.writeFileSync(abs, oldInstallerRewrite(blob(sha).toString('utf-8')));

  const res = init(p);
  assert.strictEqual(res.status, 0, res.stderr);
  assert.ok(fs.readFileSync(abs).equals(fs.readFileSync(resolveSourcePath(entry.path))),
    'the doc must now be the current shipped version');
});
