#!/usr/bin/env node
/**
 * subagent-card — generate the subagent rules card from the T0 blocks of the project CLAUDE.md.
 *
 * Every subagent except `Explore` re-loads CLAUDE.md + the auto-memory index on every request
 * (~18.6k tokens on one measured workspace). An agent that sets `omitClaudeMd: true` loads neither,
 * and Reads this card instead. The card is GENERATED — CLAUDE.md stays the single source of truth;
 * a block enters the card by being wrapped in `<!-- card:t0 -->` … `<!-- /card:t0 -->`.
 * Opt-in: with no markers in CLAUDE.md this script does nothing and --check passes.
 *
 * Usage: node <this file>            print the card
 *        node <this file> --write    write .claude/cards/subagent-card.md
 *        node <this file> --check    exit 1 when the card is missing or stale
 *
 * The same bytes ship in two kits (as .js and .cjs, under scripts/ or scripts/ck/), so paths are
 * resolved at runtime rather than written into the text.
 */
const fs = require('fs');
const path = require('path');

/** CLAUDE_PROJECT_DIR, else the parent of the `.claude/` directory this file sits under. */
function projectRoot() {
  if (process.env.CLAUDE_PROJECT_DIR) return process.env.CLAUDE_PROJECT_DIR;
  let d = __dirname;
  while (path.basename(d) !== '.claude' && path.dirname(d) !== d) d = path.dirname(d);
  return path.basename(d) === '.claude' ? path.dirname(d) : process.cwd();
}

const ROOT = projectRoot();
const SELF = path.relative(ROOT, __filename);
const SRC = path.join(ROOT, 'CLAUDE.md');
const OUT = path.join(ROOT, '.claude', 'cards', 'subagent-card.md');
const OPEN = '<!-- card:t0 -->';
const CLOSE = '<!-- /card:t0 -->';

function build(src) {
  const lines = src.split('\n');
  const out = [];
  let heading = null, emitted = null, inBlock = false, blocks = 0;
  for (const [i, line] of lines.entries()) {
    const t = line.trim();
    if (t === OPEN) {
      if (inBlock) throw new Error(`CLAUDE.md:${i + 1} nested ${OPEN}`);
      inBlock = true; blocks++;
      if (heading && heading !== emitted && !/^#/.test((lines[i + 1] || '').trim())) {
        out.push('', heading.replace(/^#+/, '###')); emitted = heading;
      }
      continue;
    }
    if (t === CLOSE) {
      if (!inBlock) throw new Error(`CLAUDE.md:${i + 1} ${CLOSE} without ${OPEN}`);
      inBlock = false; continue;
    }
    if (/^#{2,4} /.test(t)) {
      heading = t;
      if (inBlock) { out.push('', t.replace(/^#+/, '###')); emitted = t; continue; }
    }
    if (inBlock) out.push(line);
  }
  if (inBlock) throw new Error(`unterminated ${OPEN}`);
  if (!blocks) return null;
  return [
    '# Subagent rules card (T0) — GENERATED, do not edit',
    '',
    `> Generated by \`${SELF}\` from the ${blocks} \`card:t0\` blocks of the project \`CLAUDE.md\`,`,
    '> which stays the source of truth. You were started without `CLAUDE.md` and the memory index: these are the',
    '> rules that bind every task here. When the task reaches beyond them, Read the `CLAUDE.md` section it',
    '> concerns before acting.',
    ...out,
    '',
  ].join('\n').replace(/\n{3,}/g, '\n\n');
}

const src = fs.existsSync(SRC) ? fs.readFileSync(SRC, 'utf8') : '';
const card = build(src);
const arg = process.argv[2];
if (card === null) {
  // Opt-in mechanism: no markers means the project does not use a card.
  if (arg === '--check') { console.log('subagent card: not in use (no card:t0 blocks)'); process.exit(0); }
  if (arg === '--write') { console.log('subagent card: no card:t0 blocks in CLAUDE.md — nothing written'); process.exit(0); }
  process.exit(0);
}
if (arg === '--write') {
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, card);
  console.log(`wrote ${path.relative(ROOT, OUT)} (${Buffer.byteLength(card)} bytes)`);
} else if (arg === '--check') {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  if (cur === card) { console.log('subagent card: in sync'); process.exit(0); }
  console.log(cur === null ? `subagent card: MISSING — run node ${SELF} --write` : `subagent card: STALE — CLAUDE.md T0 blocks changed; run node ${SELF} --write`);
  process.exit(1);
} else {
  process.stdout.write(card);
}
